### ISSUE TITLE
It would be stopped when the scene was more then 2 lines in safari , while take a long time ,all the scene will be appear

### ISSUE THREAD

**Issue by wang125309** [Zhouzi/TheaterJS#67] opened 2017-06-16 06:01 UTC

**Comment by Zhouzi** [comment] 2017-06-17 20:13
Thanks for reporting @wang125309 👍 

With what version of Safari did you notice this? Was it on a mobile phone? Could you reproduce it in other browsers or Safari is only browser concerned? Could you share the code you used?

If you have an online link to share with me, it would be super awesome 💪

**Comment by wang125309** [comment] 2017-11-24 10:01
Im so sorry, I almost forgot that, maybe I used other modules or I was give up writing that. My safari version maybe 11.0.1 and on mobile phone the problems may be more ~ thx

**Comment by Zhouzi** [comment] 2019-07-04 14:26
I'm afraid I'll have to close this issue as I am unable to reproduce it. Do not hesitate to reopen if you're still having any trouble 👍

**Closed by Zhouzi** 2019-07-04 14:26 UTC
